// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvqnhwilhhkpvrqwnppl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cW5od2lsaGhrcHZycXducHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTk3NzgsImV4cCI6MjA1ODk5NTc3OH0.IV6dIIDjrSsR8Sou2F3fqkup6PzdNNDEPzlMkPQ-q8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);